import Head from 'next/head';
import Link from 'next/link';
import { loginAction } from '../../redux/actions/auth.actions';
import { useState } from 'react';
import { useDispatch } from 'react-redux';
import Router from "next/router";

const Login = () => {
  const dispatch = useDispatch()
  const[login, setLogin] = useState({
    name: "",
    password: ""
  })

  const handleLogin = (e) => {
    e.preventDefault();
    dispatch(loginAction(e, login, setLogin))
    // Router.push('/')
  }
  return ( 
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap" rel="stylesheet"></link>
      </Head>
      <div className="flex flex-col h-screen bg-gray-100">
        <div className="grid place-items-center mx-2 my-20 sm:my-auto">
          <div className="w-11/12 p-12 sm:w-8/12 md:w-6/12 lg:w-5/12 2xl:w-4/12 px-6 py-10 sm:px-10 sm:py-6 bg-white rounded-lg shadow-md lg:shadow-lg">
            <h2 className="text-center font-poppins font-semibold text-3xl lg:text-4xl text-orange">
              Login
            </h2>
            <form 
              className="mt-10"
              onSubmit={handleLogin}
            >
              <label className="block font-poppins text-xs font-semibold text-gray uppercase">
                Username
              </label>
              <input 
                id="name" 
                type="name" 
                name="name" 
                placeholder="Your Username" 
                className="block w-full font-poppins py-3 px-1 mt-2 text-gray-800 appearance-none border-b-2 border-gray-100 focus:text-gray-500 focus:outline-none focus:border-gray-200"
                required
              />
              <label className="block font-poppins mt-2 text-xs font-semibold text-gray uppercase">
                Password
              </label>
              <input 
                id="password" 
                type="password" 
                name="password" 
                placeholder="Your Password" 
                className="block font-poppins w-full py-3 px-1 mt-2 mb-4 text-gray-800 appearance-none border-b-2 border-gray-100 focus:text-gray-500 focus:outline-none focus:border-gray-200"
                required 
              />
              <button 
                type="submit"
                className="w-full py-3 mt-5 font-poppins bg-orange rounded-sm font-medium text-white uppercase focus:outline-none hover:bg-gray-700 hover:shadow-none"
              >
                Login
              </button>
              <div className="sm:flex sm:flex-wrap mt-8 sm:mb-4 text-sm text-center">
                <Link href="/register" className="flex-2 underline">
                  <p className="font-poppins">
                    Create an Account
                  </p>
                </Link>
              </div>
            </form>
          </div>
        </div>
      </div>
    </>
   );
}
 
export default Login;