import Head from 'next/head';
import Link from 'next/link';
import { useState, useEffect } from 'react';

const Register = () => {
  const [register, setRegister] = useState({
    name:"",
    email:"",
    password:""
  })
  const handleChange = (e) => {
    setRegister({
      ...register,
      [e.target.name]: e.target.value
    })
  }
  return (  
    <>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col h-screen bg-gray-100">
        <div className="grid place-items-center mx-2 my-20 sm:my-auto">
          <div className="w-11/12 p-12 sm:w-8/12 md:w-6/12 lg:w-5/12 2xl:w-4/12 px-6 py-10 sm:px-10 sm:py-6 bg-white rounded-lg shadow-md lg:shadow-lg">
            <h2 className="text-center font-semibold text-3xl lg:text-4xl text-orange">
              Register
            </h2>
            <form className="mt-10">
              <label className="block text-xs font-semibold text-gray uppercase">
                Name
              </label>
              <input 
                value={register.name}
                onChange={handleChange}
                id="name" 
                type="name" 
                name="name" 
                placeholder="Your Name" 
                className="block w-full py-3 px-1 mt-2 text-gray-800 appearance-none border-b-2 border-gray-100 focus:text-gray-500 focus:outline-none focus:border-gray-200"
                required
              />
              <label className="block text-xs font-semibold text-gray uppercase mt-2">
                E-mail
              </label>
              <input 
                value={register.email}
                onChange={handleChange}
                id="email" 
                type="email" 
                name="email" 
                placeholder="Your E-mail Address" 
                className="block w-full py-3 px-1 mt-2 text-gray-800 appearance-none border-b-2 border-gray-100 focus:text-gray-500 focus:outline-none focus:border-gray-200"
                required
              />
              <label className="block mt-2 text-xs font-semibold text-gray uppercase">
                Password
              </label>
              <input 
                value={register.password}
                onChange={handleChange}
                id="password" 
                type="password" 
                name="password" 
                placeholder="Your Password" 
                className="block w-full py-3 px-1 mt-2 mb-4 text-gray-800 appearance-none border-b-2 border-gray-100 focus:text-gray-500 focus:outline-none focus:border-gray-200"
                required 
              />
              <button 
                type="submit"
                className="w-full py-3 mt-5 bg-orange rounded-sm font-medium text-white uppercase focus:outline-none hover:bg-gray-700 hover:shadow-none"
              >
                Register
              </button>
              <div className="sm:flex sm:flex-wrap mt-8 sm:mb-4 text-sm text-center">
                <Link href="/login" className="flex-2 underline">
                  Already have Account?
                </Link>
              </div>
            </form>
          </div>
        </div>
      </div>
    </>
  );
}
 
export default Register;