import Head from 'next/head'

const Register = () => {
  return (  
    <div>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <h1>Register</h1>
      </main>
    </div>
  );
}
 
export default Register;