import Head from 'next/head'
import { useSelector, useDispatch} from 'react-redux';
import { useRouter } from 'next/router';
import { useEffect } from 'react'
import { getArticleById } from '../../redux/actions/article.actions';
import Navbar from '../../components/Navbar';
import SocialDetails from '../../components/SocialDetails';
import Author from '../../components/Author';
import Comment from '../../components/Comment';
import moment from 'moment';

const DetailsArticle = () => {
  const router = useRouter()
  let { id } = router.query
  const dispatch = useDispatch()
  const articleByID = useSelector((state) => state.handleArticle.dataById)
  const loading = useSelector((state) => state.handleArticle.isLoading)
  const isLogin = useSelector((state) => state.handleAuth.isLogged)
  
  useEffect(() => {
    dispatch(getArticleById(id))
  }, [dispatch, id])
  
  return (
    <div>
      <Head>
        <title>Details Article</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Cabin:wght@400;700&display=swap" rel="stylesheet"></link>
      </Head>
      <Navbar isLogin={isLogin}/>
      <main>
        {loading
          ?
          <div>
            <h1 className="text-center mt-20 text-3xl font-bold">
              Please wait...
            </h1>
          </div>
          :
            <div className="my-10 px-6 xl:px-10 2xl:px-16 w-full max-w-4xl mx-auto">
              <div className="flex flex-col">
                <h1 className="font-normal text-4xl font-cabin">
                  {articleByID.title}
                </h1>
                <div className="flex flex-row mt-5">
                  <span className="mr-4 font-normal text-base text-blue font-cabin">
                    {articleByID.category}
                  </span>
                  <p className="font-normal text-base text-grey font-cabin">
                    {moment(articleByID.date).format('MMMM Do YYYY')}
                  </p>
                </div>
              </div>
              <img 
                src={articleByID.image}
                alt={articleByID.title}
                className="my-4"
              />
              <div className="">
                <p className="text-xl leading-8 font-cabin">
                  {articleByID.description}
                </p>
              </div>
              <SocialDetails />
              <Author />
              <Comment isLogin={isLogin}/>
            </div>
        }
      </main>
    </div>
  );
}
 
export default DetailsArticle;