import Head from 'next/head'
import Article from '../components/Article'
import Navbar from '../components/Navbar'
import Searchbar from '../components/Searchbar'
import Footer from '../components/Footer';
import { useSelector, useDispatch} from 'react-redux';
import { useEffect, useState } from 'react'
import { getArticle } from '../redux/actions/article.actions';

export default function Home() {
  const dispatch = useDispatch()
  const articles = useSelector((state) => state.handleArticle.data)
  const loading = useSelector((state => state.handleArticle.isLoading))
  const searchArticle = useSelector((state) => state.handleArticle.categoryArticle)
  const [searchName, setSearchName] = useState("")
  const searchNameArticle = () => {
    articles.filter((item) => {

    })
  }

  useEffect(() => {
    dispatch(getArticle())
  }, [dispatch, searchArticle])

  return (
    <div>
      <Head>
        <title>Designate.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Cabin:wght@400;700&display=swap" rel="stylesheet"></link>
      </Head>
      
      <main>
        <Navbar />
        <Searchbar 
          articles = {articles ? articles : []} 
          searchName = {searchName}
          setSearchName = {setSearchName}
          searchNameArticle = {searchNameArticle}
        />
        {loading 
          ?
            <div>
              <h1 className="text-center mt-20 text-3xl font-bold">
                Please wait...
              </h1>
            </div>
          :
            <Article 
              articles = {articles ? articles : []} 
              searchName = {searchName}
              setSearchName = {setSearchName}
              searchNameArticle = {searchNameArticle}
            />
        }
        <Footer />
      </main>
    </div>
  )
}
